# Generated by Django 5.0.6 on 2024-08-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightFinderAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='card',
            field=models.CharField(default='UFC 999', max_length=100),
        ),
        migrations.AddField(
            model_name='fight',
            name='title',
            field=models.CharField(default='dana vs trump', max_length=100),
        ),
    ]
