# Generated by Django 5.0.6 on 2024-08-18 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightFinderAPI', '0002_fight_card_fight_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmarked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
